//
// Created by damian on 19.12.17.
//

#ifndef NET_SIMULATION_SPECIFICTURNSREPORTNOTIFIER_H
#define NET_SIMULATION_SPECIFICTURNSREPORTNOTIFIER_H


class SpecificTurnsReportNotifier {

};


#endif //NET_SIMULATION_SPECIFICTURNSREPORTNOTIFIER_H
